[profile.default]
solc-version = "0.8.13"
optimizer = false # faster compilation
optimizer-runs = 1000000
# via_ir = true
verbosity = 3                 # The verbosity of tests

ignored_error_codes = [
    2018 # function state mutability can be restricted to view
]

[profile.intense.fuzz]
runs = 1000