[profile.default]
solc-version = "0.8.15"
optimizer = false # faster compilation
optimizer-runs = 10_000_000
# via_ir = true
verbosity = 3                 # The verbosity of tests

ignored_error_codes = [
    2018 # function state mutability can be restricted to view
]
